name: CI con Maven

on:
  push:
    [cite_start]branches: [ "main" ] # Se ejecuta al hacer push [cite: 11]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el proyecto
      [cite_start]uses: actions/checkout@v4 # Paso: descargar proyecto [cite: 12]

    - name: Configurar Java 17
      [cite_start]uses: actions/setup-java@v4 # Paso: configurar Java [cite: 13, 21]
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Ejecutar pruebas Maven
      [cite_start]run: mvn test # Paso: ejecutar pruebas [cite: 14, 30]
