name: CI con Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # AMPLIACIÓN: Estrategia de matriz para probar en múltiples versiones de Java
    strategy:
      matrix:
        java-version: [11, 17, 21]

    steps:
    - name: Descargar el proyecto
      uses: actions/checkout@v4

    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }} # Lee la versión de la matriz
        distribution: 'temurin'
        cache: maven

    # AMPLIACIÓN: Cambiamos 'mvn test' por 'mvn verify'
    - name: Ejecutar pruebas y verificar con Maven
      run: mvn clean verify
